version: 0.0.3

services:
  golangserver:
    build: ./server
    restart: always
    network_mode: host
    ports:
      - 50051:50051

  golangclient:
    build: ./client
    restart: always
    network_mode: host
    ports:
      - 8080:8080
