// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/main.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	GetBooksStorage(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*BooksReply, error)
	CreateBookStorage(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookReply, error)
	DeleteBookStorage(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetBooksStorage(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*BooksReply, error) {
	out := new(BooksReply)
	err := c.cc.Invoke(ctx, "/main.Greeter/GetBooksStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateBookStorage(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookReply, error) {
	out := new(CreateBookReply)
	err := c.cc.Invoke(ctx, "/main.Greeter/CreateBookStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) DeleteBookStorage(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookReply, error) {
	out := new(DeleteBookReply)
	err := c.cc.Invoke(ctx, "/main.Greeter/DeleteBookStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	GetBooksStorage(context.Context, *GetBooksRequest) (*BooksReply, error)
	CreateBookStorage(context.Context, *CreateBookRequest) (*CreateBookReply, error)
	DeleteBookStorage(context.Context, *DeleteBookRequest) (*DeleteBookReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) GetBooksStorage(context.Context, *GetBooksRequest) (*BooksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooksStorage not implemented")
}
func (UnimplementedGreeterServer) CreateBookStorage(context.Context, *CreateBookRequest) (*CreateBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBookStorage not implemented")
}
func (UnimplementedGreeterServer) DeleteBookStorage(context.Context, *DeleteBookRequest) (*DeleteBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookStorage not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_GetBooksStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBooksStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Greeter/GetBooksStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBooksStorage(ctx, req.(*GetBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateBookStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateBookStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Greeter/CreateBookStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateBookStorage(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_DeleteBookStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeleteBookStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Greeter/DeleteBookStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeleteBookStorage(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBooksStorage",
			Handler:    _Greeter_GetBooksStorage_Handler,
		},
		{
			MethodName: "CreateBookStorage",
			Handler:    _Greeter_CreateBookStorage_Handler,
		},
		{
			MethodName: "DeleteBookStorage",
			Handler:    _Greeter_DeleteBookStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/main.proto",
}
